[program:crontab]
process_name=%(program_name)s_%(process_num)02d
command=supercronic /var/www/app/crontab
autostart=true
autorestart=true
user=root
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:task-queue-default]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/app/artisan queue:work --tries=1 --daemon --timeout=0
autostart=true
autorestart=true
user=root
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
